linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0