name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup environment variables
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=testuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=testpass" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Run unit tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: testuser
          DB_PASSWORD: testpass
          DB_NAME: testdb
        run: go test -v ./...

build-docker:
  runs-on: ubuntu-latest
  needs: lint-and-test
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        cp .env.example .env
        sed -i 's/^DB_HOST=.*/DB_HOST=postgres/' .env
        sed -i 's/^DB_PORT=.*/DB_PORT=5432/' .env
        sed -i 's/^DB_USER=.*/DB_USER=postgres/' .env
        sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=postgres/' .env
        sed -i 's/^DB_NAME=.*/DB_NAME=urlshortener/' .env
        sed -i 's/^PORT=.*/PORT=8080/' .env

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: olesianov/short-links:latest